language: node_js
node_js:
  - "10"
deploy:
  - provider: elasticbeanstalk
    region: ap-southeast-2
    env: openlawnz-api-dev-env
    app: "OpenLaw NZ"
    backet_name: openlawnz-api-deploy
    bucket_path: dev
    zip_file: "dist/dist.zip"
    skip_cleanup: true
    on:
      branch: dev
