version: "3"
services:
  app:
    image: node:alpine
    working_dir: /openlawnz/app
    # build: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - .:/openlawnz/app/
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
volumes:
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: //c/data
      o: bind